def clear_labels(self):
    self.emoji_label.clear()
    self.emoji_label_advanced.clear()
    self.description_label.clear()
    self.description_label_advanced.clear()
    self.clouds_label.clear()
    self.humidity_label.clear()
    self.wind_speed_label.clear()
    self.clouds_label_advanced.clear()
    self.humidity_label_advanced.clear()
    self.wind_speed_label_advanced.clear()
    self.wind_direction_label.clear()
    self.wind_gust_label.clear()
    self.visibility_label.clear()
    self.pressure_label.clear()
    self.sunrise_label.clear()
    self.sunset_label.clear()
    self.dt_label.clear()
    self.dt_label_advanced.clear()
    self.temp_min_label.clear()
    self.temp_max_label.clear()
    self.feels_like_temp_label.clear()
    self.country_label.clear()


def display_error(self, message):
    self.temperature_label.setStyleSheet("font-size: 30px;")
    self.temperature_label_advanced.setStyleSheet("font-size: 30px;")
    self.temperature_label.setText(message)
    self.temperature_label_advanced.setText(message)
    clear_labels(self)